{
 "title": "ServiceTopology",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Services",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(traces_spanmetrics_calls_total[$__range])))"
    }
   },
   {
    "name": "Spans",
    "query": {
     "query": "label_values({__name__=~\".*\",service_name=~\"$Services\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Metrics To Trace Routes",
   "type": "servicemap-panel",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (client, server)(rate(traces_service_graph_request_total{}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (client, server)(rate(traces_service_graph_request_failed_total{}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate( traces_spanmetrics_calls_total{}[$__range])) by (service_name,http_method,http_status_code,span_kind,span_name,status_code) >0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate( traces_spanmetrics_calls_total{}[$__range])) by (service_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate( traces_spanmetrics_calls_total{}[$__range])) by (service_name,span_kind)>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "traces_spanmetrics_calls_total",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate( traces_spanmetrics_calls_total{}[$__range])) by (service_name,http_method,http_status_code,span_kind,span_name,status_code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "traces_service_graph_request_total ",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "sum by (client, server,failed)(rate(traces_service_graph_request_total{}[$__range]))",
       "legendFormat": "all/{{client}}->{{server}}"
      }
     ]
    },
    {
     "title": "traces_service_graph_request_failed_total ",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 13, "y": 17 },
     "targets": [
      {
       "expr": "sum by (client, server,failed)(rate(traces_service_graph_request_failed_total{}[$__range]))",
       "legendFormat": "all/{{client}}->{{server}}"
      }
     ]
    },
    {
     "title": "Grand-request_total ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(traces_service_graph_request_total{}[$__range]))",
       "legendFormat": "all/{{client}}->{{server}}"
      }
     ]
    },
    {
     "title": "Grand-failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(traces_service_graph_request_failed_total{}[$__range]))",
       "legendFormat": "all/{{client}}->{{server}}"
      }
     ]
    }
   ]
  }
 ]
}