# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Jaeger
    uid: webstore-traces
    type: jaeger
    url: http://jaeger:16686/jaeger/ui
    editable: true
    isDefault: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'webstore-metrics'
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: 'Prometheus'
        tags: [ { key: 'service.name', value: 'service' }]
        queries:
          - name: 'Rate query'
            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))'
